# Copy MiniFT8_Merged_Auto.bin to the hash-first name in merged_bin_name.txt.
if(NOT BUILD_DIR)
  message(FATAL_ERROR "copy_named_merged_bin.cmake needs BUILD_DIR")
endif()
set(name_file "${BUILD_DIR}/generated/merged_bin_name.txt")
set(src "${BUILD_DIR}/MiniFT8_Merged_Auto.bin")
if(NOT EXISTS "${src}")
  message(WARNING "Merged bin missing: ${src}")
  return()
endif()
if(NOT EXISTS "${name_file}")
  message(WARNING "Build identity name missing: ${name_file}")
  return()
endif()
file(READ "${name_file}" dest_name)
string(STRIP "${dest_name}" dest_name)
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy "${src}" "${BUILD_DIR}/${dest_name}")
message(STATUS "Copied merged image to ${dest_name}")
